### ISSUE TITLE
Broken hyperlinks in programming manual

### ISSUE THREAD

**Issue by intelagense** [onitama/OpenHSP#28]
The English and Japanese manuals have a broken hyperlink in the "Quick Start" section.
[v36/doclib/hspprog.htm](https://www.onionsoft.net/hsp/v36/doclib/hspprog.htm#QUICK_START)
[v36en/doclib/hspprog.htm](https://www.onionsoft.net/hsp/v36en/doclib/hspprog.htm#QUICK_START)
Both have a link to `beginner/start.htm` which does not exist.
A working destination appears to be `beginner/COVER.HTM`

Not sure if the links should be corrected in the manuals or if the target should be renamed.

**Comment by onitama** [comment]
Thank you for your suggestion.
As for beginner/start.htm, we have not yet included it in the repository because its contents are out of date and not compatible with the Linux version.
The Windows version is included in the archive.
We will include the Linux version in the documentation in the future.
